name: Terraform Runner

on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string
      project_id:
        required: true
        type: string
      action:
        required: true
        type: string      # plan | apply | destroy

permissions:
      id-token: write
      contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working_dir }}

    steps:
      - uses: actions/checkout@v4

      - name: Auth GCP
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ inputs.project_id }}
          workload_identity_provider: projects/223480410234/locations/global/workloadIdentityPools/github/providers/health-tourism-actions
          service_account: medical@${{ inputs.project_id }}.iam.gserviceaccount.com

      - uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        if: inputs.action == 'plan' || inputs.action == 'apply'
        run: terraform plan -var="project_id=${{ inputs.project_id }}"

      - name: Apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve -var="project_id=${{ inputs.project_id }}"

      - name: Destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -auto-approve -var="project_id=${{ inputs.project_id }}"