apiVersion: v1
kind: Service
metadata:
  name: medical-tourism-service
  # Note: A Kubernetes Service LoadBalancer can only select pods in the SAME namespace it is created in.
  # To manually switch traffic between blue and green, you must apply this service manifest to the target namespace:
  # e.g., `kubectl apply -f service-active.yaml -n green`
  # And verify the selector below matches the color you want in that namespace.
  labels:
    app: medical-tourism
spec:
  type: LoadBalancer # Provisions a GCP External Network Load Balancer
  selector:
    app: medical-tourism
    # THIS IS THE SWITCH: Change this to 'green' to route traffic to the green deployment
    color: blue 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
