apiVersion: v1
kind: Service
metadata:
  name: medical-tourism-service
  labels:
    app: medical-tourism
spec:
  # Use LoadBalancer if you are on a cloud provider (AWS, GCP, Azure) to get an external IP
  # Use ClusterIP if you are using an Ingress controller
  # Use NodePort for local testing (Minikube)
  type: LoadBalancer 
  selector:
    app: medical-tourism
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
