name: Infra Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "plan | apply | destroy"
        required: true
        default: "plan"
        type: choice
        options: [plan, apply, destroy]

permissions:
  id-token: write
  contents: read

jobs:
  manual-deploy:
    # Note: When using 'uses' for a reusable workflow, you cannot have 'runs-on' or 'environment' in the same job.
    # The environment and runs-on are defined inside the reusable workflow (terraform.yml) itself.
    uses: ./.github/workflows/terraform.yml
    with:
      working_dir: ./gcp-infra
      project_id: ${{ vars.GCP_PROJECT_ID }}
      action: ${{ inputs.action }}
